config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users

  mount Sidekiq::Web => '/admin/sidekiq'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :tournaments

  get '/settings', to: 'user_settings#show'
  match 'settings/edit' => 'user_settings#edit', via: :get, as: :edit_settings
  put '/settings', to: 'user_settings#update', via: :put, as: :update_settings

  resources :alleys
  resources :addresses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tournament.rb
# frozen_string_literal: true

class Tournament < ApplicationRecord
  # enum difficulty: { HOUSE: 'HOUSE', CHALLENGE: 'CHALLENGE', SPORT: 'SPORT' }
  # enum participants: { MENS: 'MENS', WOMENS: 'WOMENS', MIXED: 'MIXED', YOUTH: 'YOUTH' }
  # enum events: {
  #   SINGLES: 'SINGLES', DOUBLES: 'DOUBLES', TEAM: 'TEAM',
  #   DUTCH: 'DUTCH', BAKER: 'BAKER', OTHER: 'OTHER'
  # }
  has_one_attached :flyer

  belongs_to :alley

  # validate :correct_document_mime_type
  validate :contact_email_or_phone_present

  validates :alley, presence: true
  validates :difficulty, presence: true
  validates :events, presence: true
  validates :participants, presence: true
  validates :starts_at, presence: true
  validates :contact_name, presence: true


  # after_create :notify_new_tournament

  EVENT_OPTIONS = %i[SINGLES DOUBLES TEAM DUTCH BAKER OTHER].freeze
  PARTICIPANTS_OPTIONS = %i[MENS WOMENS MIXED YOUTH].freeze
  DIFFICULTY_OPTIONS = %i[HOUSE CHALLENGE SPORT].freeze

  def events_enum
    EVENT_OPTIONS
  end

  def participants_enum
    PARTICIPANTS_OPTIONS
  end

  def difficulty_enum
    DIFFICULTY_OPTIONS
  end

  private

  def notify_new_tournament
    Notifications::Service.new.tournament_notify(id: id)
  end

  def array_to_hash(arr)
    hash = {}
    arr.each do
      hash[arr.to_sym] = arr
    end
    hash
  end

  def correct_document_mime_type
    return unless document.attached? && !document.content_type.in?(%w(image/png image/jpeg application/pdf))

    document.purge # delete the uploaded file
    errors.add(:document, 'Must be a pdf, png, jpeg, or jpg file')
  end

  def contact_email_or_phone_present
    return if contact_phone.present? || contact_email.present?

    errors.add(:contact_email, 'or contact phone must be present')
    errors.add(:contact_phone, 'or contact email must be present')
  end
end

app/controllers/tournaments_controller.rb
# frozen_string_literal: true

class TournamentsController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update new create]

  DEFAULT_MONTHS_IN_ADVANCE = 6
  DEFAULT_MILES = 50

  before_action :set_tournament, only: %i[show edit update destroy]
  before_action :alleys, only: %i[new edit]

  # GET /tournaments or /tournaments.json
  def index
    set_tournament_query_params

    tournaments = fetch_tournaments_by_date_range
    @tournaments = filter_tournaments_by_distance(tournaments)
  end

  # GET /tournaments/1 or /tournaments/1.json
  def show; end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit; end

  # POST /tournaments or /tournaments.json
  def create
    attributes = tournament_params.to_h.except!('start_date', 'start_time')
    date = tournament_params['start_date']
    time = tournament_params['start_time']
    event_datetime = DateTime.parse("#{date} #{time}")

    attributes['starts_at'] = event_datetime.to_s
    @tournament = Tournament.new(attributes)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1 or /tournaments/1.json
  def update
    attributes = tournament_params.to_h.except!('start_date', 'start_time')
    date = tournament_params['start_date']
    time = tournament_params['start_time']
    binding.pry
    event_datetime = DateTime.parse("#{date} #{time}")

    attributes['starts_at'] = event_datetime.to_s

    respond_to do |format|
      if @tournament.update(attributes)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1 or /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tournament
    @tournament = Tournament.find(params[:id])
  end

  def alleys
    @alleys ||= Alley.joins(:address).select('alleys.id, alleys.name, addresses.city, addresses.state').order(:name)
  end

  def index_params
    params.permit(:miles, :zip_code, :months)
  end

  # Only allow a list of trusted parameters through.
  def tournament_params
    params.require(:tournament).permit(
      :name, :alley_id, :start_date, :start_time, :contact_name, :contact_email,
      :contact_phone, :difficulty, :flyer, events: [], participants: []
    )
  end

  # TODO: Move to tournament service
  def filter_tournaments_by_distance(tournaments)
    zip_code = index_params[:zip_code]
    return tournaments unless zip_code.present?

    miles = index_params[:miles]&.to_i || DEFAULT_MILES

    tournaments.find_all do |tournament|
      alley_address = tournament.alley.address
      distance = Geocoder::Calculations.distance_between(
        alley_address.geolocation, Geocoder.coordinates(zip_code)
      )
      distance <= miles
    end
  end

  def fetch_tournaments_by_date_range
    months = index_params[:months]&.to_i || DEFAULT_MONTHS_IN_ADVANCE
    range = [DateTime.current..months.months.from_now]

    Tournament.where(starts_at: range)
  end

  def set_tournament_query_params
    return unless current_user

    return if request.query_parameters.any?

    redirect_to(
      controller: :tournaments,
      action: :index,
      tournaments: @tournaments || [],
      zip_code: current_user.user_setting.zip_code,
      miles: current_user.user_setting.notification_search_radius,
      months: current_user.user_setting.notification_period.max.days.in_months.ceil
    )
  end
end

app/helpers/tournaments_helper.rb
# frozen_string_literal: true

module TournamentsHelper
  def date_from_datetime(datetime)
    return unless datetime

    datetime.to_date
  end

  def time_from_datetime(datetime)
    return unless datetime

    "#{datetime.time.hour}:#{datetime.time.min}"
  end
end

app/views/tournaments/_form.html.erb
<%= javascript_pack_tag 'tournament_form', 'data-turbolinks-track': 'reload' %>

<%= form_with(model: tournament) do |form| %>
  <% if tournament.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <strong><%= pluralize(tournament.errors.count, "error") %> prohibited this tournament from being saved:</strong>

      <ul>
        <% tournament.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :alley_id, class: 'form-label' %>
    <%= form.select(:alley_id,
                    options_for_select(@alleys.map{|a| ["#{a.name} - #{a.city}, #{a.state}", a.id]}),
                    { },
                    {id: 'tournament_alley_id', class: 'form-control selectpicker', prompt: 'Select One', 'data-live-search': "true"}
        )
    %>
    <small id="emailHelp" class="form-text text-primary"><%= link_to 'Alley not found? Add new Alley', new_alley_path %></small>
  </div>

  <div class="form-group">
    <div class="form-label">Date</div>
    <%= form.text_field :start_date, type: 'date', class: 'form-control', min: Date.today, value: date_from_datetime(@tournament.starts_at) %>

  </div>

  <div class="form-group">
    <div class="form-label">Start Time</div>
    <%= form.text_field :start_time, type: 'time', class: 'form-control', value: time_from_datetime(@tournament.starts_at) %>
  </div>

  <div class="form-group">
    <%= form.label :difficulty, class: 'form-label' %>
    <% Tournament::DIFFICULTY_OPTIONS.each do |option| %>
      <div class="form-radio">
        <%= form.radio_button(:difficulty, option, { id: option, class: 'form-radio-input' } ) %>
        <%= form.label option.capitalize, for: option, class: 'form-radio-label' %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :events, class: 'form-label' %>
    <% Tournament::EVENT_OPTIONS.each do |option| %>
      <div class="form-check"
      <%= form.check_box(:events, { id: option, :multiple => true, class: 'form-check-input', checked: tournament&.events&.include?(option.to_s) }, option) %>
      <%= form.label option.capitalize, for: option, class: 'form-check-label' %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :participants, class: 'form-label' %>
    <% Tournament::PARTICIPANTS_OPTIONS.each do |participant_option| %>
      <div class="form-check"
        <%= form.check_box(:participants, { id: participant_option, :multiple => true, class: 'form-check-input', checked: tournament&.participants&.include?(participant_option.to_s) }, participant_option) %>
        <%= form.label participant_option.capitalize, for: participant_option, class: 'form-check-label' %>
      </div>
    <% end %>
  </div>

  <h2>Contact Info</h2>

  <div class="form-group">
    <%= form.label :contact_name, class: 'form-label' %>
    <%= form.text_field :contact_name, class: 'form-control', value: tournament&.contact_name || current_user.full_name %>
  </div>

  <div class="form-group">
    <%= form.label :contact_email, class: 'form-label' %>
    <%= form.text_field :contact_email, class: 'form-control', type: 'email', value: tournament&.contact_email || current_user.email %>
  </div>

  <div class="form-group">
    <%= form.label :contact_phone, class: 'form-label' %>
    <%= form.text_field :contact_phone, class: 'form-control', type: 'tel', value: tournament&.contact_phone || current_user.phone_number %>
  </div>

  <div class="row">
    <div class="col-4">
      <div class="form-group">
        <label class="btn btn-primary">
          Upload a flyer
          <span style="display:none;">
            <%= form.file_field :flyer, required: false, multiple: false  %>
          </span>
        </label>
        <small id="imageHelp" class="form-text">png, jpeg, jpg, or pdf</small>
      </div>
    </div>
    <div class="col-8">
      <% if @tournament.flyer.attached? %>
        <%= image_tag(@tournament.flyer, width: 500) %>
        <br>
      <% end %>
    </div>
  </div>

  <div class="form-actions">
    <%= form.submit class: 'btn btn-primary' %>
    <%= link_to 'Back', :back, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing Tournament</h1>

<%= render 'form', tournament: @tournament %>

app/views/tournaments/index.html.erb
<p id="notice"><%= notice %></p>

<%= javascript_pack_tag 'tournaments', 'data-turbolinks-track': 'reload' %>

<div class="row">
  <div class="col-md-9">
    <h1>Tournaments</h1>
  </div>
  <div class="col-md-3">
    <% if user_signed_in? %>
      <div class="actions">
        <%= button_to 'Add Tournament', new_tournament_path, class: 'btn btn-primary', method: 'get' %>
      </div>
    <% end %>
  </div>
</div>
<form id="search-form">
  <div class="row">
    <div class="col-md-4 form-group">
        <%= label_tag('Zip Code', nil, for: 'zip_code', class: 'form-label') %>
        <%= text_field_tag(:zip_code, nil, class: 'input form-control') %>
    </div>
    <div class="col-md-4 form-group">
        <%= label_tag('Search Radius (miles)', nil, for: 'miles', class: 'form-label') %>
        <%= select_tag(
              :miles,
              options_for_select(UserSetting::NOTIFICATION_SEARCH_RADIUS, 50),
              { class: 'selectpicker form-control', id: 'tournament-miles' }
            )%>
    </div>
    <div class="col-md-4 form-group">
        <%= label_tag('Months in Advance', nil, for: 'months', class: 'form-label') %>
        <%= select_tag(
              :months,
              options_for_select((1..12), 3),
              { class: 'selectpicker form-control', id: 'tournament-months'}
            ) %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 actions" id="search-div">
      <button id="search" class="btn btn-primary" type="submit" onclick="submitSearch()">Search</button>
      <button id="clear" class="btn btn-secondary back" type="submit" onclick="clearSearch()">Clear</button>
    </div>
  </div>
</form>
<br />
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Alley</th>
      <th>Starts at</th>
      <th>Events</th>
      <th>Difficulty</th>
      <th>Participants</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= tournament.name %></td>
        <td><%= tournament.alley.readable %></td>
        <td><%= tournament.starts_at %></td>
        <td><%= tournament.events.map(&:capitalize).join(', ') %></td>
        <td><%= tournament.difficulty.capitalize %></td>
        <td><%= tournament.participants.map(&:capitalize).join(', ') %></td>
        <td><%= link_to 'Show', tournament %></td>
        <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tournaments/new.html.erb
<h1>New Tournament</h1>

<%= render 'form', tournament: @tournament %>

app/views/tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tournament.name %>
</p>

<p>
  <strong>Alley:</strong>
  <%= @tournament.alley_id %>
</p>

<p>
  <strong>Starts at:</strong>
  <%= @tournament.starts_at %>
</p>

<p>
  <strong>Events:</strong>
  <%= @tournament.events %>
</p>

<p>
  <strong>Participants:</strong>
  <%= @tournament.participants %>
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @tournament.difficulty %>
</p>

<p>
  <strong>Flyer:</strong>
  <%= image_tag(@tournament.flyer, width: 500) if @tournament.flyer.attached? %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @tournament.contact_name %>
</p>

<p>
  <strong>Contact Email:</strong>
  <%= @tournament.contact_email %>
</p>

<p>
  <strong>Contact Phone Number:</strong>
  <%= @tournament.contact_phone %>
</p>

<%= link_to 'Edit', edit_tournament_path(@tournament) %> |
<%= link_to 'Back', tournaments_path %>