config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users

  mount Sidekiq::Web => '/admin/sidekiq'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :tournaments

  get '/settings', to: 'user_settings#show'
  match 'settings/edit' => 'user_settings#edit', via: :get, as: :edit_settings
  put '/settings', to: 'user_settings#update', via: :put, as: :update_settings

  resources :alleys
  resources :addresses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/alley.rb
# frozen_string_literal: true

require 'states'

class Alley < ApplicationRecord
  belongs_to :address
  accepts_nested_attributes_for :address,
                                allow_destroy: true,
                                reject_if: lambda { |attributes|
                                  attributes['street_address'].blank? ||
                                    attributes['city'].blank? ||
                                    attributes['state'].blank? ||
                                    attributes['zip_code'].blank?
                                }

  validates :name, presence: true
  validates :address_id, presence: true

  def readable
    "#{name} - #{address.city}, #{::STATES[address.state.to_sym]}"
  end
end

app/controllers/alleys_controller.rb
# frozen_string_literal: true

class AlleysController < ApplicationController
  before_action :set_alley, only: %i[show edit update destroy]

  # GET /alleys or /alleys.json
  def index
    @alleys = Alley.all
  end

  # GET /alleys/1 or /alleys/1.json
  def show; end

  # GET /alleys/new
  def new
    @alley = Alley.new
  end

  # GET /alleys/1/edit
  def edit; end

  # POST /alleys or /alleys.json
  def create
    @alley = Alley.new(alley_params)

    respond_to do |format|
      if @alley.save
        format.html { redirect_to @alley, notice: 'Alley was successfully created.' }
        format.json { render :show, status: :created, location: @alley }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @alley.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alleys/1 or /alleys/1.json
  def update
    respond_to do |format|
      if @alley.update(alley_params)
        format.html { redirect_to @alley, notice: 'Alley was successfully updated.' }
        format.json { render :show, status: :ok, location: @alley }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @alley.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alleys/1 or /alleys/1.json
  def destroy
    @alley.destroy
    respond_to do |format|
      format.html { redirect_to alleys_url, notice: 'Alley was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_alley
    @alley = Alley.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def alley_params
    params.require(:alley).permit(:name, address_attributes: %i[street_address secondary_address city state zip_code])
  end
end

app/helpers/alleys_helper.rb
# frozen_string_literal: true

require 'states'

module AlleysHelper
  def states_option
    ::STATES.map { |key, value| [value, key] }
  end
end

app/views/alleys/_form.html.erb
<%= javascript_pack_tag 'alleys', 'data-turbolinks-track': 'reload' %>

<%= form_with(model: alley) do |form| %>
  <% if alley.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <strong>
        <%= pluralize(alley.errors.count, "error") %> prohibited this alley from being saved:
      </strong>
      <ul>
        <% alley.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <h4 class="subtitle is-4">Address</h4>
  <%= form.fields_for :address_attributes do |address| %>
    <div class="form-group">
      <%= address.label :street_address, class: 'form-label' %>
      <%= address.text_field :street_address, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= address.label :secondary_address, class: 'form-label' %>
      <%= address.text_field :secondary_address, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= address.label :city, class: 'form-label' %>
      <%= address.text_field :city, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :state, class: 'form-label' %>
      <%= form.select(:state,
                      options_for_select(states_option),
                      { },
                      {
                        id: 'alley-state',
                        class: 'form-control selectpicker',
                        prompt: 'Select State',
                        'data-live-search': "true"
                      }
          )
      %>
    </div>

    <div class="form-group">
      <%= address.label :zip_code, class: 'form-label' %>
      <%= address.text_field :zip_code, class: 'form-control' %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
    <%= link_to 'Back', :back, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/alleys/edit.html.erb
<h1>Editing Alley</h1>

<%= render 'form', alley: @alley %>

<%= link_to 'Show', @alley %> |
<%= link_to 'Back', alleys_path %>

app/views/alleys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alleys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alleys.each do |alley| %>
      <tr>
        <td><%= alley.name %></td>
        <td><%= alley.address_id %></td>
        <td><%= link_to 'Show', alley %></td>
        <td><%= link_to 'Edit', edit_alley_path(alley) %></td>
        <td><%= link_to 'Destroy', alley, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alley', new_alley_path, class: 'button is-primary'%>

app/views/alleys/new.html.erb
<h1 class="title is-3">New Alley</h1>

<%= render 'form', alley: @alley %>

app/views/alleys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @alley.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @alley.address_id %>
</p>

<%= link_to 'Edit', edit_alley_path(@alley) %> |
<%= link_to 'Back', alleys_path %>