config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users

  mount Sidekiq::Web => '/admin/sidekiq'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :tournaments

  get '/settings', to: 'user_settings#show'
  match 'settings/edit' => 'user_settings#edit', via: :get, as: :edit_settings
  put '/settings', to: 'user_settings#update', via: :put, as: :update_settings

  resources :alleys
  resources :addresses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_setting.rb
# frozen_string_literal: true

class UserSetting < ApplicationRecord
  belongs_to :user

  before_save :compact_periods

  validates :zip_code, presence: true
  validates :notification_period, presence: true
  validates :notification_search_radius, presence: true

  NOTIFICATION_PERIODS = [0, 1, 2, 3, 7, 14, 30, 60, 90].freeze
  NOTIFICATION_SEARCH_RADIUS = [0, 5, 15, 25, 50, 100, 250, 500].freeze

  scope :notifiable, -> { where.not('notification_period @> ?', '{0}') }

  private

  def compact_periods
    notification_period.compact!

    notification_period.delete(0) if notification_period.any?(&:positive?)
  end
end

app/controllers/user_settings_controller.rb
# frozen_string_literal: true

class UserSettingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_setting, only: %i[show edit update]

  # GET /user_settings/1 or /user_settings/1.json
  def show; end

  # GET /user_settings/1/edit
  def edit; end

  # POST /user_settings or /user_settings.json
  def create
    @user_setting = UserSetting.new(user_setting_params)

    respond_to do |format|
      if @user_setting.save
        format.html { redirect_to settings_path(@user_setting), notice: 'User setting was successfully created.' }
        format.json { render :show, status: :created, location: @user_setting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_settings/1 or /user_settings/1.json
  def update
    respond_to do |format|
      if @user_setting.update(user_setting_params)
        format.html { redirect_to settings_path(@user_setting), notice: 'User setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_setting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_setting
    @user_setting = current_user.user_setting
    # UserSetting.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_setting_params
    params.require(:user_setting).permit(:notification_search_radius, :zip_code, notification_period: [])
  end
end

app/helpers/user_settings_helper.rb
# frozen_string_literal: true

module UserSettingsHelper
end

app/views/user_settings/_form.html.erb
<%= form_with(url: settings_path, method: :put, model: @user_setting) do |form| %>

  <% if user_setting.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <strong>
        <%= pluralize(user_setting.errors.count, "error") %> prohibited this user_setting from being saved:
      </strong>
      <ul>
        <% user_setting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :zip_code, class: 'form-label' %>
    <%= form.text_field :zip_code, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :notification_search_radius, class: 'form-label' %>
    <br />
    <% UserSetting::NOTIFICATION_SEARCH_RADIUS.each do |radius| %>
      <div class="form-check form-check-inline">
        <%= form.radio_button(:notification_search_radius, radius, { id: "radius-#{radius}", class: 'form-check-input' } ) %>
        <%= form.label radius > 0 ? pluralize(radius, 'mile') : "No Distance Restriction", for: "radius-#{radius}", class: 'form-check-label' %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :notification_period, class: 'form-label', class: 'form-label' %>
    <br />
    <% UserSetting::NOTIFICATION_PERIODS.each do |period| %>
      <div class="form-check form-check-inline"
        <%= form.check_box(:notification_period, { id: "period-#{period}", :multiple => true, class: 'form-check-input' }, period) %>
        <%= form.label period > 0 ? pluralize(period, 'day') : "No Notifications", for: "period-#{period}", class: 'form-check-label' %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
    <%= link_to 'Back', :back, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/user_settings/edit.html.erb
<h1>Editing User Settings</h1>

<%= render 'form', user_setting: @user_setting %>

app/views/user_settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Settings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Notification search radius</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_settings.each do |user_setting| %>
      <tr>
        <td><%= user_setting.user_id %></td>
        <td><%= user_setting.notification_search_radius %></td>
        <td><%= link_to 'Show', user_setting %></td>
        <td><%= link_to 'Edit', edit_user_setting_path(user_setting) %></td>
        <td><%= link_to 'Destroy', user_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Setting', new_user_setting_path %>

app/views/user_settings/new.html.erb
<h1>New User Setting</h1>

<%= render 'form', user_setting: @user_setting %>

app/views/user_settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zip Code:</strong>
  <%= @user_setting.zip_code %>
</p>

<p>
  <strong>Notification search radius:</strong>
  <%= @user_setting.notification_search_radius %>
</p>

<p>
  <strong>Notification period:</strong>
  <%= @user_setting.notification_period %>
</p>

<%= link_to 'Edit', edit_settings_path %> |
<%= link_to 'Back', settings_path %>